
BLENDER="C:\Program Files\Blender Foundation\Blender 3.3\blender.exe"
DIST=../dist

all : \
    $(DIST)/void.pnct \
    $(DIST)/void.scene \

$(DIST)/void.scene : hexapod.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "void.blend:Main" "$(DIST)/void.scene"

$(DIST)/void.pnct : hexapod.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "void.blend:Main" "$(DIST)/void.pnct" 
